/*
 * This source file was generated by the Gradle 'init' task
 */
package monitorczasu;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Date;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

public class App {
    
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        File plik = new File("app/src/main/resources/sesje.txt");
        String wybor;
        String wynikProgramu;
        boolean stanSesji= false;
        LocalDateTime czasStartuSesji = null;
        LocalDateTime czasZatrzymaniaSesji;
        DateTimeFormatter fromatDaty = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");


        do{
            
            System.out.println("1.Rozpocznij nowa sesje\n2.Zakoncz sesje\n3.Pokaz hostorie sesji\n4.Wyjdz\n");
            wybor = scanner.next();

            try{
                if(wybor.equals("1") && stanSesji == true){
                    throw new IllegalStateException("sesja juz istnieje!!");
                }
            }catch(IllegalStateException e){
                e.printStackTrace();
            }

            if(wybor.equals("1") && stanSesji == false){
                stanSesji = true;
                czasStartuSesji = LocalDateTime.now();
            }
            
            try{
                if(wybor.equals("2") && stanSesji == false){
                    throw new IllegalStateException("sesja nie zostala wystartowana!!");
                }
            }catch(IllegalStateException e){
                e.printStackTrace();
            }

            if(wybor.equals("2") && stanSesji == true){
                stanSesji = false;
                czasZatrzymaniaSesji = LocalDateTime.now();
                
                wynikProgramu = "["+fromatDaty.format(czasStartuSesji)+"] "+" Sesja trwała: "+obliczenieCzasuTrwaniaSesji(czasStartuSesji, czasZatrzymaniaSesji)+" minut\n";
                zapiszWynikuDoPliku(wynikProgramu);
            }

            if(wybor.equals("3")){
                try{
                    if(sprawdzenieCzyPlikInstnieje(plik) == true){
                        odczytanieWynikowZPilku(plik);
                    }else{
                        throw new IOException("Stworzono nowy plik sesje.txt mozliwy do odczytania!");
                    }
                }catch(IOException e){
                    e.printStackTrace();
                }
            }

        }while(!wybor.equals("4"));

    }

    public static boolean sprawdzenieSesji(String a){
        if(!a.equals("")){
            return true;
        }else{
            return false;
        }
    }

    public static long obliczenieCzasuTrwaniaSesji(LocalDateTime start,LocalDateTime stop){
        return Duration.between(start, stop).toMinutes();
    }

    public static void zapiszWynikuDoPliku(String n){
        try(FileWriter writer = new FileWriter("app/src/main/resources/sesje.txt", true)) {
          writer.write(n);
        } catch (IOException e) {
            e.printStackTrace();
        }finally{
            System.out.println("zapisano wynik do pliku sesje.txt");
        }
    }

    public static void odczytanieWynikowZPilku(File plik){
        try (Scanner plikScanner = new Scanner(plik)) {
            while (plikScanner.hasNextLine()) {
                String data = plikScanner.nextLine();
                System.out.println(data);
            }
        } catch (FileNotFoundException e) {
                    System.out.println("Blad!!");
                    e.printStackTrace();
        }finally{
            System.out.println("operacja udana!!");
        }
            
    }

    public static boolean sprawdzenieCzyPlikInstnieje(File file){
        if(file.exists()){
            return true;
        }else{
            
            try{
                file = new File("app/src/main/resources/sesje.txt");
                if(file.createNewFile()){
                    
                }

            }catch(IOException e){
                e.printStackTrace();
            }
            return false;
        }
    }
}
